"""Add image filename to Complaint

Revision ID: 2b3ef4d5fd7e
Revises: e183cf5bc774
Create Date: 2025-10-24 08:36:03.593458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b3ef4d5fd7e'
down_revision = 'e183cf5bc774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
