"""Add latitude longitude to Complaint

Revision ID: 558a8de03e2b
Revises: 7eb8d6b89025
Create Date: 2025-10-26 18:52:38.297526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '558a8de03e2b'
down_revision = '7eb8d6b89025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=7),
               existing_nullable=True)

    # ### end Alembic commands ###
