"""Add image_filenames to Complaint

Revision ID: 56aff2c8ebd1
Revises: 2b3ef4d5fd7e
Create Date: 2025-10-24 21:03:42.596618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56aff2c8ebd1'
down_revision = '2b3ef4d5fd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filenames', sa.Text(), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_filenames')

    # ### end Alembic commands ###
