"""Add resolution fields

Revision ID: 7eb8d6b89025
Revises: 56aff2c8ebd1
Create Date: 2025-10-25 07:30:20.422257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb8d6b89025'
down_revision = '56aff2c8ebd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resolved_images', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_column('resolved_images')
        batch_op.drop_column('resolution_note')

    # ### end Alembic commands ###
